---
<<<<<<< HEAD
- name: install the haproxy and keepalived services on the node
  import_tasks: install_services.yml
=======
- name: install the haproxy service on the node
  import_tasks: install_haproxy.yml
>>>>>>> 8892280c6b2da5cb01a132740ad9577e6c201b41

- name: move all files to the HAPROXY node
  import_tasks: move_files.yml

<<<<<<< HEAD
- name: restart the HAPROXY and KEEPALIVED services
  import_tasks: restart_services.yml
=======
- name: restart the HAPROXY service
  import_tasks: restart_haproxy.yml
>>>>>>> 8892280c6b2da5cb01a132740ad9577e6c201b41
