---
web_files_location_local: /home/automation/new_branch/roles/config-webservers/files
web_files_destenation: /var/www/html
httpd_conf_dest: /etc/httpd/conf
<<<<<<< HEAD
=======
ssl_dir: /var/www/html/ssl
shared_web_files_source: /home/automation/new_branch/roles/config-webservers/files
shared_ssl_files_dest: /var/www/html/ssl
>>>>>>> f1eabf1770d8dac62b9892df7c54654e2cc30ff8
