---
- name: move index.html to the server
  copy:
<<<<<<< HEAD
    src: /home/automation/plays/config-webservers/files/{{hostname}}/{{item}}
    dest: /var/www/html/{{item}}
    owner: root
    group: root
  with_items:
    - index.html
    - image.jpeg

- name: create the ssl directory under the right place
  file:
    path: /var/www/html/ssl
    state: directory
    mode: '0755'

- name: move the ssl files to the server
  copy:
    src: /home/automation/plays/config-webservers/files/{{hostname}}/{{item}}
    dest: /var/www/html/ssl/{{item}}
    owner: root
    group: root
  with_items:
    - cert.crt
    - private.key

- name: move the httpd.conf file
  copy:
    src: /home/automation/plays/config-webservers/files/{{hostname}}/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
=======
    src: /home/automation/plays/config-webservers/files/{{hostname}}/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root

- name: move keepalived.conf to the server
  copy:
    src: /home/automation/plays/config-webservers/files/{{hostname}}/keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    mode: 0666

- name: move keepalived health script to the server
  copy:
    src: /home/automation/plays/config-webservers/files/{{hostname}}/check.sh
    dest: /etc/keepalived/check.sh
    mode: 0757
>>>>>>> 8892280c6b2da5cb01a132740ad9577e6c201b41
